### ISSUE TITLE
PA_MPJPE calculation failed! svd_cuda: (Batch element 0): The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated singular values (error code: 55).

### ISSUE THREAD

**Issue by jiheeyang** [Arthur151/ROMP#136]
Hi, I have difficulty training for the 6 dataset(mpiinf, coco, mpii, lsp, muco, crowdpose). The training code can run successfully for a period of time (not more than some epoch) and then will encounter this error in the training logs file.  Can you give me a solution for this?

>6epoch
![image](https://user-images.githubusercontent.com/29176256/147876046-2679b5f3-2eda-46bb-8315-ce3eaa99cf4e.png)
![image](https://user-images.githubusercontent.com/29176256/147876064-45c2e673-c7b6-4755-9163-3237e711d78b.png)

>7epoch

**Comment by Arthur151** [comment]
Sorry about that!
It seems that the training is not converged. The loss is quite huge. When `PA_MPJPE calculation failed` occurs, it means that the training is completely failed. 

Could you please share the configuration .yml file for training? Especially the batch size you set. Did you start training from the pre-train model?

**Comment by jiheeyang** [comment]
This is the configuration .yml file for training .
I changed GPUS, datasets, and sample_prob in configs/v1.yml.


```
ARGS:
 tab: 'V1_hrnet' 
 dataset: 'mpiinf,coco,mpii,lsp,muco,crowdpose'
 GPUS: 0,1,
 distributed_training: False
 model_version: 1
 pretrain: 'imagenet'
 match_preds_to_gts_for_supervision: True

 master_batch_size: -1
 val_batch_size: 16
 batch_size: 64
 nw: 4
 nw_eval: 2
 lr: 0.00005

 fine_tune: False
 fix_backbone_training_scratch: False
 eval: False
 supervise_global_rot: False

 model_return_loss: False
 collision_aware_centermap: True
 collision_factor: 0.2
 homogenize_pose_space: True
 shuffle_crop_mode: True
 shuffle_crop_ratio_2d: 0.1
 shuffle_crop_ratio_3d: 0.4

 merge_smpl_camera_head: False
 head_block_num: 2

 backbone: 'hrnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2

 model_path: None

loss_weight:
  MPJPE: 200.
  PAMPJPE: 360.
  P_KP2D: 400.
  Pose: 80.
  Shape: 6.
  Prior: 1.6
  CenterMap: 160.

sample_prob:
 h36m: 0.0
 mpiinf: 0.16
 coco: 0.2
 lsp: 0.16
 mpii: 0.2
 muco: 0.14
 crowdpose: 0.14
```
