### ISSUE TITLE
Shape mismatch in ROMP validation

### ISSUE THREAD

**Issue by xljh0520** [Arthur151/ROMP#291]
Hi, I found another bug during validation. Two tensor shape mismatch [here](https://github.com/Arthur151/ROMP/blob/master/romp/lib/evaluation/evaluation_matrix.py#L311).

Here is my config
```

ARGS:
 tab: 'V1_resnet' 
 dataset: 'h36m,coco,mpii,muco,crowdpose,lsp'
 gpu: 0
 distributed_training: False
 model_version: 1
 match_preds_to_gts_for_supervision: True

 master_batch_size: -1
 val_batch_size: 16
 batch_size: 32
 nw: 4
 nw_eval: 2
 lr: 0.00005

 fine_tune: False
 fix_backbone_training_scratch: False
 eval: False
 supervise_global_rot: False

 model_return_loss: True
 collision_aware_centermap: True
 collision_factor: 0.2
 homogenize_pose_space: True
 shuffle_crop_mode: True
 shuffle_crop_ratio_2d: 0.1
 shuffle_crop_ratio_3d: 0.4

 merge_smpl_camera_head: False
 head_block_num: 2

 backbone: 'resnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2

 model_path: None
 test_interval: 200

loss_weight:
  MPJPE: 200.
  PAMPJPE: 360.
  P_KP2D: 400.
  Pose: 80.
  Shape: 6.
  Prior: 1.6
  CenterMap: 160.
  Cam: 200.

sample_prob:
 h36m: 0.2
 coco: 0.2
 lsp: 0.16
 mpii: 0.16
 muco: 0.14
 crowdpose: 0.14
```
