### ISSUE TITLE
Heatmaps Do not look as expexted????

### ISSUE THREAD

**Issue by mkhoshle** [Arthur151/ROMP#316]
Hello,

I have trained ROMP on the `pw3d` dataset for 150 epochs and from SCRATCH. Here are my hyperparameters:
```
ARGS:
 tab: 'V1_hrnet' 
 dataset: 'pw3d'
 GPUS: 0,1,2,3
 distributed_training: False
 model_version: 1
 match_preds_to_gts_for_supervision: True

 master_batch_size: -1
 val_batch_size: 16
 batch_size: 16
 epoch: 150
 nw: 4
 nw_eval: 2
 lr: 0.00005
 exp: 'ROMP'              # experiment name
 save_dir: './results'           # Path to results directory

 fine_tune: True
 fix_backbone_training_scratch: False
 eval: True
 supervise_global_rot: False

 model_return_loss: True
 collision_aware_centermap: True
 collision_factor: 0.2
 homogenize_pose_space: True
 shuffle_crop_mode: True
 shuffle_crop_ratio_2d: 0.1
 shuffle_crop_ratio_3d: 0.4

 merge_smpl_camera_head: False
 head_block_num: 2

 backbone: 'hrnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2

 model_path: None

loss_weight:
 MPJPE: 200.
 PAMPJPE: 360.
 P_KP2D: 400.
 Pose: 80.
 Shape: 6.
 Prior: 1.6
 CenterMap: 160.

sample_prob:
 pw3d: 1
```
The model seems to be well converged and here is the loss function:
<img width="433" alt="Screen Shot 2022-07-19 at 5 29 03 PM" src="https://user-images.githubusercontent.com/21323137/179852481-90262d53-0205-4366-a2b2-d46a351bdeb6.png">

However, when I look at the Center-map heatmaps it doe
<img width="1033" alt="Screen Shot 2022-07-19 at 5 27 16 PM" src="https://user-images.githubusercontent.com/21323137/179852604-71ee525b-97ed-4dff-93df-2a3a73bbfd86.png">
s not look good at all:

I expected to get a plot similar to below that I obtained by fine-tuning the ROMP with HRNet-32 as the backbone (V1_hrnet_3dpwft.sh):
<img width="1234" alt="Screen Shot 2022-07-15 at 4 52 37 PM" src="https://user-images.githubusercontent.com/21323137/179852819-04c84b8b-8af6-4d50-8f29-76c0ef7be9f8.png">

Any thought or advice on why this is the case and what I further need to do to improve the center map heatmap?

Thanks in advance,
